_extends: .github
repository:
  name: homebrew-formulas
  description: A collection of Homebrew formulas
  topics: homebrew
  allow_auto_merge: true
  private: false
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
